config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/about', to: 'home#about'
  resources :recipes, only:  [:show, :create, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def about ; end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = set_recipe()
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:alert] = 'Receita criada'
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = 'Policia do zap, parado'
      render :new
    end
  end
  
  def new
    @recipe = Recipe.new
  end

  private

  def set_recipe
    recipe = Recipe.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type, :cuisine, :difficulty, :cook_time, :ingredients, :cook_method)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about.html.erb
<div class="container">
  <h1>BANANAS IN PIJAMAS</h1>

</div>

app/views/home/index.html.erb
<div class="container">
  <div class="jumbotron">
  <h1 class="display-4">CookBook</h1>
  <p class="lead"Bem-vindo ao maior livro de receitas online</p>
  <hr class="my-4">
  <p>Bem-vindo ao maior livro de receitas online </p>
  <%= link_to 'Saiba Mais', about_path, class: "btn btn-primary btn-lg", role: "button" %>
  <%= link_to 'Enviar uma receita', new_recipe_path, class:"btn btn-primary btn-lg"  %>
</div>



  <% @recipes.each do |recipe|  %>
    <h1><%= link_to recipe.title, recipe %></h1>
    <ul>
      <li><%= recipe.recipe_type %></li>
      <li><%= recipe.cuisine %></li>
      <li><%= recipe.difficulty %></li>
      <li><%= recipe.cook_time %> minutos</li>
    </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= alert %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/new.html.erb
<%= form_for(@recipe, :html => {class:'form-horizontal', role:'form'}) do |f|  %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :title, 'Título' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :title, class:'form-control', placeholder: 'Título da receita', autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-12">
      <%= f.label :recipe_type, 'Tipo da Receita' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :recipe_type, class:'form-control', placeholder: 'Receitas sao variadas', autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-12">
      <%= f.label :cuisine, 'Cozinha' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :cuisine, class:'form-control', placeholder: '', autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-12">
      <%= f.label :difficulty, 'Dificuldade' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :difficulty, class:'form-control', placeholder: '', autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-12">
      <%= f.label :cook_time, 'Tempo de Preparo' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :cook_time, class:'form-control', placeholder: '', autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-12">
      <%= f.label :ingredients, 'Ingredientes' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :ingredients, class:'form-control', placeholder: '', autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-12">
      <%= f.label :cook_method, 'Como Preparar' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :cook_method, class:'form-control', placeholder: '', autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-sm-offset-2 col-sm-10'>
    <%= f.submit 'Enviar', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/recipes/show.html.erb
<div class="container">
  <h1><%= @recipe.title %></h1>
  <h3>Detalhes</h3>
  <p><%= @recipe.recipe_type %></p>
  <p><%= @recipe.cuisine %></p>
  <p><%= @recipe.difficulty %></p>
  <p><%= @recipe.cook_time%> minutos </p>
  <h3>Ingredientes</h3>
  <p><%= @recipe.ingredients %></p>
  <h3>Como Preparar</h3>
  <p><%= @recipe.cook_method %></p>

<%= link_to 'Voltar', root_path, class: "btn btn-primary"%>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <%= link_to 'CookBook', root_path, class: "navbar-brand" %>  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Recipe</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Extra</a>
      </li>
    </ul>
  </div>
</nav>